# Generated by Django 3.1.2 on 2020-10-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Изображение 7'),
        ),
    ]
