# Generated by Django 3.0 on 2020-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201019_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=1, upload_to='media/products', verbose_name='Изображение 2'),
            preserve_default=False,
        ),
    ]
